name: Prod Deploy

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./event-website/
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: FTP Deploy 
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: sftp://ssh.strato.de:22/event-website
        ftp-username: dev.space-4.de
        ftp-password: ${{ secrets.STRATO_MASTERPASSWORD }}
        git-ftp-args: --insecure

    - name: Send Success Push Notification
      uses: techulus/push-github-action@1.0.0
      if: success()
      env:
        API_KEY: ${{ secrets.TECHULUSPUSHAPIKEY }}
        MESSAGE: "Deployment in Event-Website erfolgreich durchgelaufen! ✅"
        TITLE: Testing
        
    
    - name: Send failure Push Notification
      uses: techulus/push-github-action@1.0.0
      if: failure()
      env:
        API_KEY: ${{ secrets.TECHULUSPUSHAPIKEY }}
        MESSAGE: "Deployment in Event-Website ist ge-failed! ❌"
        TITLE: Testing
