name: Prod Deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./philtrum-run
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: npm install
      run: npm install

    - name: npm run bundle
      run: npm run bundle

    - name: FTP Deploy 
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ssh.strato.de
        username: dev.space-4.de
        password: ${{ secrets.STRATO_MASTERPASSWORD }}
        protocol: ftps
        port: 22
        local-dir: ./philtrum-run
