name: Prod Deploy

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./philtrum-run
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: FTP Deploy 
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ssh.strato.de
        ftp-username: dev.space-4.de
        ftp-password: ${{ secrets.STRATO_MASTERPASSWORD }}
        local-dir: /philtrum-run/
